export interface FuncionarioInterface {

  idFuncionario: number,
  nome: string,
  setor: number,
  horario: number,
  ctps: string,
  escoail: string,
  funcao: number,
  admissao: string,
  demissao: string,
  cpf: string,
  rg: string,
  eleitor: string,
  pis: string,
  transporte: string,
  alimentacao: string,
  nascimento: string,
  pai: string,
  mae: string,
  cep: string,
  endereco: string,
  numero: string,
  bairro: string,
  cidade: string,
  uf: string,
  telefone: string,
  celular: string,
  ativo: boolean
}