services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: .
    container_name: finance-backend
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    volumes:
      - ./finance-backend/uploads:/app/uploads
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend  
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
